### ISSUE TITLE
broken conversion???

### ISSUE THREAD

**Issue by peppobon** [transpect/docx2hub#12]
When converting, just after the docx has been unzipped, I get this error:
...
[info] Unzip finished successfully.
Message: Mode: insert-xpath
ERROR: file:/xxxxxxxxxx/docx2hub/xpl/mathtype2mml.xpl:119:49:Undeclared input port 'additional-font-maps' on step tr:mathtype2mml named convert-wmf at file:/xxxxxxx/docx2hub/xpl/mathtype2mml.xpl:119

Note that I call docx2hub:convert passing in
<p:with-option name="mathtype2mml" select="'no'"/>

**Comment by peppobon** [comment]
the full error stack is this:

Message: Mode: insert-xpath
ERROR: file:/xxxxxx/docx2hub/xpl/mathtype2mml.xpl:119:49:Undeclared input port 'additional-font-maps' on step tr:mathtype2mml named convert-wmf at file:/xxxxxx/docx2hub/xpl/mathtype2mml.xpl:119
ERROR: file:/xxxxxx/docx2hub/xpl/mathtype2mml.xpl:139:53:Undeclared input port 'additional-font-maps' on step tr:mathtype2mml named convert-ole at file:/xxxxxx/docx2hub/xpl/mathtype2mml.xpl:139
ERROR: err:XS0010:Undeclared input port 'additional-font-maps' on step tr:mathtype2mml named convert-wmf at file:/xxxxxx/docx2hub/xpl/mathtype2mml.xpl:119
ERROR: err:XS0010:Undeclared input port 'additional-font-maps' on step tr:mathtype2mml named convert-wmf at file:/xxxxxx/updoc-2/docx2hub/xpl/mathtype2mml.xpl:119
ERROR: err:XS0010:Undeclared input port 'additional-font-maps' on step tr:mathtype2mml named convert-wmf at file:/xxxxxx/docx2hub/xpl/mathtype2mml.xpl:119

**Comment by peppobon** [comment]
the second trace is when calling docx2hub:convert passing in
<p:with-option name="mathtype2mml" select="'yes'"/>

**Comment by gimsieke** [comment]
I think you need an updated XML Calabash runtime including the MathType extension with [tr:mathtype2mml](https://github.com/transpect/mathtype-extension/blob/master/xpl/mathtype2mml-declaration.xpl).
I don’t know whether you are using our Calabash distribution via git or svn? For git, you need to update https://github.com/transpect/calabash-frontend recursively. For svn, you need to use/update https://subversion.le-tex.de/common/github-mirror/calabash_1.15_saxon_9.6/

**Comment by peppobon** [comment]
Thanks Gerritt,
I indeed forgot to made a recursive update to calabash.

Now it works
