### ISSUE TITLE
WMF equations are not Converted

### ISSUE THREAD

**Issue by sathishvelu1984** [transpect/docx2hub#23]
[Sample Wmf.docx](https://github.com/transpect/docx2hub/files/4671415/Sample.Wmf.docx)
Math object not converted, when it is in WMF image format
Instead of mathml output i get just this

`<para><mediaobject><imageobject><imagedata fileref="SampleWmf.docx.tmp/word/media/image1.wmf" css:width="117.5pt" css:height="56.1pt"/></imageobject></mediaobject></para>`

**Comment by gimsieke** [comment]
I haven’t explored why, but there seem to be two issues. The first is that somehow the converter thinks that the WMF doesn’t contain MTEF. This apparently can be overcome by invoking `docx2hub.xpl` with `mathtype2mml=wmf+try-all-pict-wmf`, as documented [here](https://github.com/transpect/docx2hub/blob/master/xpl/mathtype2mml.xpl#L66). 
The second problem is that the equation will be discarded in a subsequent conversion step, maybe because it’s the only element in the paragraph. I will look into this bug later today.

**Comment by sathishvelu1984** [comment]
> I haven’t explored why, but there seem to be two issues. The first is that somehow the converter thinks that the WMF doesn’t contain MTEF. This apparently can be overcome by invoking `docx2hub.xpl` with `mathtype2mml=wmf+try-all-pict-wmf`, as documented [here](https://github.com/transpect/docx2hub/blob/master/xpl/mathtype2mml.xpl#L66).
> The second problem is that the equation will be discarded in a subsequent conversion step, maybe because it’s the only element in the paragraph. I will look into this bug later today.

Thanks for your quick reply,
I changed the option to wmf+try-all-pict-wmf, and tried running, the sub file inside mathtype2mathml/cleanip.xml contains the required mathml and it is not coming inside the document.xml
I have a docx file with many paragraphs and equations(wmf), for sample purpose i have extracted single equation to post here

**Comment by gimsieke** [comment]
I won’t do anything about the necessity to use `mathtype2mml=wmf+try-all-pict-wmf` right now, this is an option that you need to set. It seems that the ordinary `wmf` option only looks at WMFs embedded in `v:shape/v:imagedata`, while in your example the WMF was embedded in a `w:drawing//a:blip`. 

About the 2nd issue, I committed a fix. It might fail if multiple WMFs are embedded in a single `w:drawing`. 

Please test with your complete example (after pulling the most recent commit from this repo) at let me know whether it works.

**Comment by sathishvelu1984** [comment]
> I won’t do anything about the necessity to use `mathtype2mml=wmf+try-all-pict-wmf` right now, this is an option that you need to set. It seems that the ordinary `wmf` option only looks at WMFs embedded in `v:shape/v:imagedata`, while in your example the WMF was embedded in a `w:drawing//a:blip`.
> 
> About the 2nd issue, I committed a fix. It might fail if multiple WMFs are embedded in a single `w:drawing`.
> 
> Please test with your complete example (after pulling the most recent commit from this repo) at let me know whether it works.

Thanks for the quick update, extracted file seems to work fine, but i tried the main docx and it fails again, i will attach the docx here
[Sample.docx](https://github.com/transpect/docx2hub/files/4675579/Sample.docx)

**Comment by gimsieke** [comment]
Yet another way to embed MathType WMF images…
I said that the other method looks for `v:shape/v:imagedata`, and in your file we do have `v:shape/v:imagedata`. Truth is, the `wmf` method only looked for `v:shape[o:OLEObject]/v:imagedata`. I  will commit another change that will look for `v:shape`s without OLE objects and process their WMFs, if `mathtype2mml=wmf+try-all-pict-wmf` is supplied as an option.
Sigh.

**Comment by gimsieke** [comment]
@sathishvelu1984, please pull the latest commit and give it a try.

**Comment by sathishvelu1984** [comment]
> @sathishvelu1984, please pull the latest commit and give it a try.

Yes it does work now, thanks once again
