### ISSUE TITLE
keep inline styles in index terms

### ISSUE THREAD

**Issue by mkraetke** [transpect/docx2hub#26]
Inline styles in index terms are not kept. After the mode `docx2hub:remove-redundant-run-atts `, the inline styles still exist:

```xml
<w:r>
  <w:fldChar xml:id="fldChar_d3804e2370" w:fldCharType="begin"/>
</w:r>
<w:r>
  <w:instrText xml:space="preserve"> XE "α</w:instrText>
</w:r>
<w:r role="ZFTiefgestellt">
  <w:instrText>1</w:instrText>
</w:r>
<w:r>
  <w:instrText xml:space="preserve">-Adrenozeptor-Antagonist" </w:instrText>
</w:r>
<w:r>
  <w:fldChar xml:id="fldChar_d3804e2381" w:fldCharType="end"/>
</w:r>
```

However, after the mode `docx2hub:join-instrText-runs` just the string value of the node is present:

```xml
<w:r role="ZFTiefgestellt">
  <w:instrText docx2hub:fldChar-start-id="fldChar_d3804e2370" docx2hub:field-function-name="XE" docx2hub:field-function-args="&#34;α1-Adrenozeptor-Antagonist&#34;"><quot>"</quot>α1-Adrenozeptor-Antagonist<quot>"</quot>
</w:instrText>
</w:r>
```

**Comment by mkraetke** [comment]
I've attached two samples to reproduce this issue:
* [italic_in_index.docx](https://github.com/transpect/docx2hub/files/9611161/italic_in_index.docx)
* [subscript_in_index.docx](https://github.com/transpect/docx2hub/files/9611162/subscript_in_index.docx)

**Comment by gimsieke** [comment]
“Only I can fix it.”
— Donald J. Trump

**Comment by mkraetke** [comment]
And you will have Mexico pay for that fix.

**Comment by gimsieke** [comment]
[narrator] His fix did more harm than good so far

**Comment by gimsieke** [comment]
I fixed it. I’m a very stable genius.
