### ISSUE TITLE
empty index terms

### ISSUE THREAD

**Issue by mkraetke** [transpect/docx2hub#27]
It appears that inline markup in indexterms results in empty index entries such as `<indexterm/>`. A minimal sample is attached to this ticket. The first indexterm is empty, the second looks exactly like the first one, but contains no other inline markup.

**Comment by mkraetke** [comment]
[ts_std_mono_06340_index_kor.docx](https://github.com/transpect/docx2hub/files/9717253/ts_std_mono_06340_index_kor.docx)

**Comment by gimsieke** [comment]
fixed
