### ISSUE TITLE
restore mapping of (for example) Wingdings char 00E0

### ISSUE THREAD

**Issue by gimsieke** [transpect/docx2hub#8]
All mappings from Wingdings characters in the 0000…00FF range seem to have disappeared from [Wingdings.xml](https://github.com/transpect/docx2hub/blob/master/fontmaps/Wingdings.xml). 
Characters in the 0000 range are typically equivalent with the characters in the F000 range.
Include the mapping for the 00 variants, too. At least for the chars that have been included in previous versions of the mapping.

**Comment by gimsieke** [comment]
There has been a commit 4 months ago, 862d666, that introduced a mapping for 00E0. Don’t trample on other people’s delicately maintained mappings that are used in production, without providing a bridge to keep existing mappings.

**Comment by mkraetke** [comment]
There was neither a comprehensive nor a delicately maintained mapping. The Wingdings file just consisted of 46 characters  and I wonder myself why there existed a 0000 range mapping for the LEFTWARDS ARROW but not for other arrows. This looks more like a quick and dirty job and not a well-conceived approach. Previously, these were ALL existing zero range mappings:

```xml
<symbol number="004A" entity="J" char="&#x263A;" font="Segoe UI Symbol"/><!-- happy smiley -->
<symbol number="004C" entity="L" char="&#x2639;" font="Segoe UI Symbol"/><!-- sad smiley -->
<symbol number="0061" entity="&#x0061;" char="&#x264B;"/><!-- CANCER -->
<symbol number="006E" entity="" char="&#x25a0;"/><!-- BLACK SQUARE -->
<symbol number="006F" entity="o" char="&#x25A1;"/><!-- WHITE SQUARE -->
<symbol number="00E0" entity="&#x00E0;" char="&#x2192;"/><!-- RIGHTWARDS ARROW -->
<symbol number="0072" entity="&#x0072;" char="&#x2610;"/><!-- BALLOT BOX -->
<symbol number="003F" entity="&#x003F;" char="&#x2794;"/><!-- Heavy wide-headed rightwards arrow -->
<symbol number="00E8" entity="&#x00E8;" char="&#x2794;" font="Segoe UI Symbol"/><!-- Heavy wide-headed rightwards arrow -->
<symbol number="0AEA" entity="&#x0AEA;" char="&#x2794;"/><!-- Heavy wide-headed rightwards arrow -->
```

Instead I generated a new configuration where every character has a zero range mapping like this:

```xml
<!--WIDE-HEADED RIGHTWARDS BARB ARROW-->
<symbol number="F0E0" entity="&#xf0e0;" char="&#x1f86a;"/>
<symbol number="00E0" entity="&#xf0e0;" char="&#x1f86a;"/> 
```

Updated with this commit c59acc96fa56224b23cee3abdd46fd9438c59e3c
